DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS board;
DROP TABLE IF EXISTS thread;
DROP TABLE IF EXISTS boards_has_threads;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL, 
  password TEXT NOT NULL
);


CREATE TABLE board (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL, 

  link TEXT UNIQUE NOT NULL, 
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE thread (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  board_id INTEGER NOT NULL,
  parent_id INTEGER,

  img TEXT,
  title TEXT,
  body TEXT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (author_id) REFERENCES user (id),
  FOREIGN KEY (board_id) REFERENCES board (id)
);